# Data Science Tools and Ecosystems

In this notebook, Data Science tools are summarized.

**Objectives**

Some popular languages for Data Science are:
* Python
* R
* Java
* SQL
* C+

Some of the commonly used libraries used for Data Scientist include:

1. Pandas
2. NumPy
3. Seaborn
4. Keras
5. Apache Spark

| **Data Science Tools** |
| ---------------------- |
|  Anaconda   |
|  R Studio |
|   Jupyter Notebooks   |

### Below are a few examples of arithmetic expressions in Python

In [3]:
#This is a simple artihmetic expression to multiple then add integars

In [2]:
(3*4)+5

17

In [7]:
#This will convert 200 minutes to hours by dividing by 60
200//60

3

# Objectives
* Add commments to code cells
* Create markdown cells
* Add ordered and unordered lists to markdown cells
* Format content of markdown cells with heading skills

**Author(s)**

Lily S